### ISSUE TITLE
Fails to build with udp-stream@0.0.12

### ISSUE THREAD

**Issue by ephemient** [ssrlive/rust-tun#86]
```
$ cargo install tun2proxy
...
   Compiling tun2 v2.0.2
error[E0061]: this function takes 2 arguments but 1 argument was supplied
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tun2proxy-0.2.23/src/lib.rs:137:13
    |
137 |             UdpStream::from_tokio(socket).await
    |             ^^^^^^^^^^^^^^^^^^^^^-------- an argument of type `std::net::SocketAddr` is missing
    |
note: associated function defined here
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/udp-stream-0.0.12/src/lib.rs:185:18
    |
185 |     pub async fn from_tokio(
    |                  ^^^^^^^^^^
help: provide the argument
    |
137 |             UdpStream::from_tokio(socket, /* std::net::SocketAddr */).await
    |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

due to narrowlink/udp-stream#11 changed API.

**Comment by ssrlive** [comment]
```bash
cargo update
cargo build
```
